const cartas = [
    // Arcanos Mayores
    { nombre: "El Loco", imagen: "/cartas/el-loco.png" },
    { nombre: "El Mago", imagen: "/cartas/el-mago.png" },
    { nombre: "La Sacerdotisa", imagen: "/cartas/la-sacerdotisa.png" },
    { nombre: "La Emperatriz", imagen: "/cartas/la-emperatriz.png" },
    { nombre: "El Emperador", imagen: "/cartas/el-emperador.png" },
    { nombre: "El Hierofante", imagen: "/cartas/el-hierofante.png" },
    { nombre: "Los Enamorados", imagen: "/cartas/los-enamorados.png" },
    { nombre: "El Carro", imagen: "/cartas/el-carro.png" },
    { nombre: "La Fuerza", imagen: "/cartas/la-fuerza.png" },
    { nombre: "El Ermitaño", imagen: "/cartas/el-ermitano.png" },
    { nombre: "La Rueda de la Fortuna", imagen: "/cartas/la-rueda-de-la-fortuna.png" },
    { nombre: "La Justicia", imagen: "/cartas/la-justicia.png" },
    { nombre: "El Colgado", imagen: "/cartas/el-colgado.png" },
    { nombre: "La Muerte", imagen: "/cartas/la-muerte.png" },
    { nombre: "La Templanza", imagen: "/cartas/la-templanza.png" },
    { nombre: "El Diablo", imagen: "/cartas/el-diablo.png" },
    { nombre: "La Torre", imagen: "/cartas/la-torre.png" },
    { nombre: "La Estrella", imagen: "/cartas/la-estrella.png" },
    { nombre: "La Luna", imagen: "/cartas/la-luna.png" },
    { nombre: "El Sol", imagen: "/cartas/el-sol.png" },
    { nombre: "El Juicio", imagen: "/cartas/el-juicio.png" },
    { nombre: "El Mundo", imagen: "/cartas/el-mundo.png" },

    // Copas
    { nombre: "As de Copas", imagen: "/cartas/as-de-copas.png" },
    { nombre: "Dos de Copas", imagen: "/cartas/dos-de-copas.png" },
    { nombre: "Tres de Copas", imagen: "/cartas/tres-de-copas.png" },
    { nombre: "Cuatro de Copas", imagen: "/cartas/cuatro-de-copas.png" },
    { nombre: "Cinco de Copas", imagen: "/cartas/cinco-de-copas.png" },
    { nombre: "Seis de Copas", imagen: "/cartas/seis-de-copas.png" },
    { nombre: "Siete de Copas", imagen: "/cartas/siete-de-copas.png" },
    { nombre: "Ocho de Copas", imagen: "/cartas/ocho-de-copas.png" },
    { nombre: "Nueve de Copas", imagen: "/cartas/nueve-de-copas.png" },
    { nombre: "Diez de Copas", imagen: "/cartas/diez-de-copas.png" },
    { nombre: "Sota de Copas", imagen: "/cartas/sota-de-copas.png" },
    { nombre: "Caballo de Copas", imagen: "/cartas/caballo-de-copas.png" },
    { nombre: "Reina de Copas", imagen: "/cartas/reina-de-copas.png" },
    { nombre: "Rey de Copas", imagen: "/cartas/rey-de-copas.png" },

    // Bastos
    { nombre: "As de Bastos", imagen: "/cartas/as-de-bastos.png" },
    { nombre: "Dos de Bastos", imagen: "/cartas/dos-de-bastos.png" },
    { nombre: "Tres de Bastos", imagen: "/cartas/tres-de-bastos.png" },
    { nombre: "Cuatro de Bastos", imagen: "/cartas/cuatro-de-bastos.png" },
    { nombre: "Cinco de Bastos", imagen: "/cartas/cinco-de-bastos.png" },
    { nombre: "Seis de Bastos", imagen: "/cartas/seis-de-bastos.png" },
    { nombre: "Siete de Bastos", imagen: "/cartas/siete-de-bastos.png" },
    { nombre: "Ocho de Bastos", imagen: "/cartas/ocho-de-bastos.png" },
    { nombre: "Nueve de Bastos", imagen: "/cartas/nueve-de-bastos.png" },
    { nombre: "Diez de Bastos", imagen: "/cartas/diez-de-bastos.png" },
    { nombre: "Sota de Bastos", imagen: "/cartas/sota-de-bastos.png" },
    { nombre: "Caballo de Bastos", imagen: "/cartas/caballo-de-bastos.png" },
    { nombre: "Reina de Bastos", imagen: "/cartas/reina-de-bastos.png" },
    { nombre: "Rey de Bastos", imagen: "/cartas/rey-de-bastos.png" },

    // Espadas
    { nombre: "As de Espadas", imagen: "/cartas/as-de-espadas.png" },
    { nombre: "Dos de Espadas", imagen: "/cartas/dos-de-espadas.png" },
    { nombre: "Tres de Espadas", imagen: "/cartas/tres-de-espadas.png" },
    { nombre: "Cuatro de Espadas", imagen: "/cartas/cuatro-de-espadas.png" },
    { nombre: "Cinco de Espadas", imagen: "/cartas/cinco-de-espadas.png" },
    { nombre: "Seis de Espadas", imagen: "/cartas/seis-de-espadas.png" },
    { nombre: "Siete de Espadas", imagen: "/cartas/siete-de-espadas.png" },
    { nombre: "Ocho de Espadas", imagen: "/cartas/ocho-de-espadas.png" },
    { nombre: "Nueve de Espadas", imagen: "/cartas/nueve-de-espadas.png" },
    { nombre: "Diez de Espadas", imagen: "/cartas/diez-de-espadas.png" },
    { nombre: "Sota de Espadas", imagen: "/cartas/sota-de-espadas.png" },
    { nombre: "Caballo de Espadas", imagen: "/cartas/caballo-de-espadas.png" },
    { nombre: "Reina de Espadas", imagen: "/cartas/reina-de-espadas.png" },
    { nombre: "Rey de Espadas", imagen: "/cartas/rey-de-espadas.png" },

    // Oros
    { nombre: "As de Oro", imagen: "/cartas/as-de-oro.png" },
    { nombre: "Dos de Oro", imagen: "/cartas/dos-de-oro.png" },
    { nombre: "Tres de Oro", imagen: "/cartas/tres-de-oro.png" },
    { nombre: "Cuatro de Oro", imagen: "/cartas/cuatro-de-oro.png" },
    { nombre: "Cinco de Oro", imagen: "/cartas/cinco-de-oro.png" },
    { nombre: "Seis de Oro", imagen: "/cartas/seis-de-oro.png" },
    { nombre: "Siete de Oro", imagen: "/cartas/siete-de-oro.png" },
    { nombre: "Ocho de Oro", imagen: "/cartas/ocho-de-oro.png" },
    { nombre: "Nueve de Oro", imagen: "/cartas/nueve-de-oro.png" },
    { nombre: "Diez de Oro", imagen: "/cartas/diez-de-oro.png" },
    { nombre: "Sota de Oro", imagen: "/cartas/sota-de-oro.png" },
    { nombre: "Caballo de Oro", imagen: "/cartas/caballo-de-oro.png" },
    { nombre: "Reina de Oro", imagen: "/cartas/reina-de-oro.png" },
    { nombre: "Rey de Oro", imagen: "/cartas/rey-de-oro.png" }
];

export default cartas;
