const cartas = [
    // Arcanos Mayores
    { nombre: "El Loco", imagen: "/cartas/el-loco.jpg" },
    { nombre: "El Mago", imagen: "/cartas/el-mago.jpg" },
    { nombre: "La Sacerdotisa", imagen: "/cartas/la-sacerdotisa.jpg" },
    { nombre: "La Emperatriz", imagen: "/cartas/la-emperatriz.jpg" },
    { nombre: "El Emperador", imagen: "/cartas/el-emperador.jpg" },
    { nombre: "El Hierofante", imagen: "/cartas/el-hierofante.jpg" },
    { nombre: "Los Enamorados", imagen: "/cartas/los-enamorados.jpg" },
    { nombre: "El Carro", imagen: "/cartas/el-carro.jpg" },
    { nombre: "La Fuerza", imagen: "/cartas/la-fuerza.jpg" },
    { nombre: "El Ermitaño", imagen: "/cartas/el-ermitano.jpg" },
    { nombre: "La Rueda de la Fortuna", imagen: "/cartas/la-rueda-de-la-fortuna.jpg" },
    { nombre: "La Justicia", imagen: "/cartas/la-justicia.jpg" },
    { nombre: "El Colgado", imagen: "/cartas/el-colgado.jpg" },
    { nombre: "La Muerte", imagen: "/cartas/la-muerte.jpg" },
    { nombre: "La Templanza", imagen: "/cartas/la-templanza.jpg" },
    { nombre: "El Diablo", imagen: "/cartas/el-diablo.jpg" },
    { nombre: "La Torre", imagen: "/cartas/la-torre.jpg" },
    { nombre: "La Estrella", imagen: "/cartas/la-estrella.jpg" },
    { nombre: "La Luna", imagen: "/cartas/la-luna.jpg" },
    { nombre: "El Sol", imagen: "/cartas/el-sol.jpg" },
    { nombre: "El Juicio", imagen: "/cartas/el-juicio.jpg" },
    { nombre: "El Mundo", imagen: "/cartas/el-mundo.jpg" },
  
    // Copas
    { nombre: "As de Copas", imagen: "/cartas/as-de-copas.jpg" },
    { nombre: "Dos de Copas", imagen: "/cartas/dos-de-copas.jpg" },
    { nombre: "Tres de Copas", imagen: "/cartas/tres-de-copas.jpg" },
    { nombre: "Cuatro de Copas", imagen: "/cartas/cuatro-de-copas.jpg" },
    { nombre: "Cinco de Copas", imagen: "/cartas/cinco-de-copas.jpg" },
    { nombre: "Seis de Copas", imagen: "/cartas/seis-de-copas.jpg" },
    { nombre: "Siete de Copas", imagen: "/cartas/siete-de-copas.jpg" },
    { nombre: "Ocho de Copas", imagen: "/cartas/ocho-de-copas.jpg" },
    { nombre: "Nueve de Copas", imagen: "/cartas/nueve-de-copas.jpg" },
    { nombre: "Diez de Copas", imagen: "/cartas/diez-de-copas.jpg" },
    { nombre: "Sota de Copas", imagen: "/cartas/sota-de-copas.jpg" },
    { nombre: "Caballo de Copas", imagen: "/cartas/caballo-de-copas.jpg" },
    { nombre: "Reina de Copas", imagen: "/cartas/reina-de-copas.jpg" },
    { nombre: "Rey de Copas", imagen: "/cartas/rey-de-copas.jpg" },
  
    // Bastos
    { nombre: "As de Bastos", imagen: "/cartas/as-de-bastos.jpg" },
    { nombre: "Dos de Bastos", imagen: "/cartas/dos-de-bastos.jpg" },
    { nombre: "Tres de Bastos", imagen: "/cartas/tres-de-bastos.jpg" },
    { nombre: "Cuatro de Bastos", imagen: "/cartas/cuatro-de-bastos.jpg" },
    { nombre: "Cinco de Bastos", imagen: "/cartas/cinco-de-bastos.jpg" },
    { nombre: "Seis de Bastos", imagen: "/cartas/seis-de-bastos.jpg" },
    { nombre: "Siete de Bastos", imagen: "/cartas/siete-de-bastos.jpg" },
    { nombre: "Ocho de Bastos", imagen: "/cartas/ocho-de-bastos.jpg" },
    { nombre: "Nueve de Bastos", imagen: "/cartas/nueve-de-bastos.jpg" },
    { nombre: "Diez de Bastos", imagen: "/cartas/diez-de-bastos.jpg" },
    { nombre: "Sota de Bastos", imagen: "/cartas/sota-de-bastos.jpg" },
    { nombre: "Caballo de Bastos", imagen: "/cartas/caballo-de-bastos.jpg" },
    { nombre: "Reina de Bastos", imagen: "/cartas/reina-de-bastos.jpg" },
    { nombre: "Rey de Bastos", imagen: "/cartas/rey-de-bastos.jpg" },
  
    // Espadas
    { nombre: "As de Espadas", imagen: "/cartas/as-de-espadas.jpg" },
    { nombre: "Dos de Espadas", imagen: "/cartas/dos-de-espadas.jpg" },
    { nombre: "Tres de Espadas", imagen: "/cartas/tres-de-espadas.jpg" },
    { nombre: "Cuatro de Espadas", imagen: "/cartas/cuatro-de-espadas.jpg" },
    { nombre: "Cinco de Espadas", imagen: "/cartas/cinco-de-espadas.jpg" },
    { nombre: "Seis de Espadas", imagen: "/cartas/seis-de-espadas.jpg" },
    { nombre: "Siete de Espadas", imagen: "/cartas/siete-de-espadas.jpg" },
    { nombre: "Ocho de Espadas", imagen: "/cartas/ocho-de-espadas.jpg" },
    { nombre: "Nueve de Espadas", imagen: "/cartas/nueve-de-espadas.jpg" },
    { nombre: "Diez de Espadas", imagen: "/cartas/diez-de-espadas.jpg" },
    { nombre: "Sota de Espadas", imagen: "/cartas/sota-de-espadas.jpg" },
    { nombre: "Caballo de Espadas", imagen: "/cartas/caballo-de-espadas.jpg" },
    { nombre: "Reina de Espadas", imagen: "/cartas/reina-de-espadas.jpg" },
    { nombre: "Rey de Espadas", imagen: "/cartas/rey-de-espadas.jpg" },
  
    // Oros
    { nombre: "As de Oros", imagen: "/cartas/as-de-oros.jpg" },
    { nombre: "Dos de Oros", imagen: "/cartas/dos-de-oros.jpg" },
    { nombre: "Tres de Oros", imagen: "/cartas/tres-de-oros.jpg" },
    { nombre: "Cuatro de Oros", imagen: "/cartas/cuatro-de-oros.jpg" },
    { nombre: "Cinco de Oros", imagen: "/cartas/cinco-de-oros.jpg" },
    { nombre: "Seis de Oros", imagen: "/cartas/seis-de-oros.jpg" },
    { nombre: "Siete de Oros", imagen: "/cartas/siete-de-oros.jpg" },
    { nombre: "Ocho de Oros", imagen: "/cartas/ocho-de-oros.jpg" },
    { nombre: "Nueve de Oros", imagen: "/cartas/nueve-de-oros.jpg" },
    { nombre: "Diez de Oros", imagen: "/cartas/diez-de-oros.jpg" },
    { nombre: "Sota de Oros", imagen: "/cartas/sota-de-oros.jpg" },
    { nombre: "Caballo de Oros", imagen: "/cartas/caballo-de-oros.jpg" },
    { nombre: "Reina de Oros", imagen: "/cartas/reina-de-oros.jpg" },
    { nombre: "Rey de Oros", imagen: "/cartas/rey-de-oros.jpg" }
  ];
  
  export default cartas;
  